---
- hosts: all

  tasks:

    - file:
        dest: ~/.config/nvim
        state: directory

    - file:
        src: "{{ curdir }}/files/vimrc"
        dest: ~/.config/nvim/init.vim
        state: link

    - file: path=~/.local/share/nvim/site/autoload state=directory recurse=Yes
      with_items:
        - autoload

    - get_url:
        force: yes
        dest: ~/.local/share/nvim/site/autoload/plug.vim
        url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"

    # - file: path=~/.vim/spell state=directory
